In [60]:
import numpy as np
import pandas as pd
from plotnine import *

foodiex = pd.read_csv('2020-XTern-DS.csv')
y = ','
foodiex['maincuisine'] = foodiex['Cuisines'].apply(lambda x: x if y not in x else x[0:x.index(",")])
foodiex['Cook_Time'] = foodiex['Cook_Time'].apply(lambda x: x[0:x.index(' ')])
foodiex['Cook_Time'] = foodiex['Cook_Time'].apply(lambda x: int(x))
foodiex['counts'] = foodiex.groupby('maincuisine')['maincuisine'].transform('count')
cooktimecuisine = foodiex.groupby('maincuisine').agg('mean')
newcookcuisine = cooktimecuisine.sort_values(by = ['Cook_Time'])
newcookcuisine = newcookcuisine[newcookcuisine['counts'] > 5]
newcookcuisine = newcookcuisine.drop(columns = ['Latitude', 'Longitude'])
print('Least amount of Cook Time among Cuisines with more than 5 restaurants')
print(newcookcuisine.head(10))
print('\n')
print('Most amount of Cook Time among Cuisines with more than 5 restaurants')
print(newcookcuisine.tail(10))
newcookcuisine

Least amount of Cook Time among Cuisines with more than 5 restaurants
               Cook_Time  counts
maincuisine
Paan           30.000000     7.0
Momos          30.000000     8.0
Ice Cream      31.500000    30.0
Lebanese       32.500000     6.0
Bengali        33.461538    13.0
Beverages      33.877551    49.0
Maharashtrian  34.166667    12.0
Pizza          34.215686    51.0
South Indian   34.696970   132.0
Fast Food      34.800000   225.0


Most amount of Cook Time among Cuisines with more than 5 restaurants
             Cook_Time  counts
maincuisine
Sandwich     38.636364    11.0
Continental  38.750000    24.0
Andhra       40.000000     8.0
Burger       40.400000    25.0
Cafe         40.733333    75.0
Bakery       43.506494    77.0
Italian      43.600000    25.0
Salad        44.375000     8.0
Mishti       46.666667     9.0
Asian        48.181818    11.0

               Cook_Time  counts
maincuisine
Paan           30.000000     7.0
Momos          30.000000     8.0
Ice Cream      31.500000    30.0
Lebanese       32.500000     6.0
Bengali        33.461538    13.0
Beverages      33.877551    49.0
Maharashtrian  34.166667    12.0
Pizza          34.215686    51.0
South Indian   34.696970   132.0
Fast Food      34.800000   225.0
European       35.000000     6.0
Desserts       35.000000    61.0
Kerala         35.555556     9.0
Street Food    35.555556    54.0
Juices         35.625000     8.0
Chinese        35.817610   159.0
Biryani        35.824742    97.0
Mithai         35.978261    46.0
Rolls          36.250000    24.0
American       36.428571     7.0
Healthy Food   36.500000    20.0
Mughlai        36.551724    29.0
Arabian        36.666667     9.0
North Indian   37.825371   607.0
Sandwich       38.636364    11.0
Continental    38.750000    24.0
Andhra         40.000000     8.0
Burger         40.400000    25.0
Cafe           40.733333    75.0
Bakery         43.506494    77.0
Italian        43.600000    25.0
Salad          44.375000     8.0
Mishti         46.666667     9.0
Asian          48.181818    11.0